main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('recipes/', include('recipes.urls')),
    path('', include('recipes.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'
urlpatterns = [
    path('index', views.index, name='index'),
    path('', views.index, name='index'),
    path('recipe/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('recipe/<int:recipe_id>/review', views.add_review, name='add_review'),
    path('recipe/new/', views.new_recipe, name='new_recipe'),
]

recipes/models.py
from django.db import models

class Recipe(models.Model):
    name = models.CharField(max_length=220)
    description = models.TextField(blank=True, null=True)
    instructions = models.TextField(blank=True, null=True)
    prep_time = models.CharField(max_length=50, blank=True, null=True)
    cook_time = models.CharField(max_length=50, blank=True, null=True)
    photo = models.ImageField(upload_to='recipe_photos', blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredientName = models.CharField(max_length=220)
    quantity = models.CharField(max_length=50)

    def __str__(self):
        return self.ingredientName

class Review(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    title = models.CharField(max_length=220)
    comment = models.TextField(blank=True, null=True)
    rating = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

recipes/forms.py
from django import forms
from django.forms import formset_factory
from .models import Recipe, Ingredient

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('name', 'description', 'instructions', 'prep_time', 'cook_time', 'photo')

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ('ingredientName', 'quantity')
        labels = {
            'ingredientName': 'Name',
        }

ingredientFormSet = formset_factory(IngredientForm, extra=1)

recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.views.decorators import csrf
from django.forms import formset_factory


from .models import Recipe, Ingredient, Review
from .forms import RecipeForm, IngredientForm

# Create your views here.
def index(request):
    recipe_list = Recipe.objects.all()
    context = {
        'recipe_list' : recipe_list,
    }
    return render(request, 'recipes/index.html', context)


def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    return render(request, 'recipes/recipe_detail.html', {'recipe': recipe})

def add_review(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    try:
        rating = int(request.POST['rating'])
        comment = request.POST['comment']
    except (KeyError, ValueError):
        return render(request, 'recipes/recipe_detail.html', {
            'recipe': recipe,
            'error_message': "You didn't provide a rating or a comment",
        })
    else:
        Review.objects.create(recipe=recipe, rating=rating, comment=comment)
        return render(request, 'recipes/recipe_detail.html', {'recipe': recipe})

def new_recipe(request):
    ingredientFormSet = formset_factory(IngredientForm, extra=1)
    if request.method == 'POST':
        formRecipe = RecipeForm(request.POST, request.FILES)
        formset = ingredientFormSet(request.POST)
        # formIngredient = IngredientForm(request.POST)

        if formRecipe.is_valid() and formset.is_valid():
            recipe = formRecipe.save()
            for ingredient in formset:
                ingredient = ingredient.save(False)
                ingredient.recipe = recipe
                # Do not save the ingredient if it is empty
                if ingredient.ingredientName != '':
                    ingredient.save()

            # ingredient = formIngredient.save(False)
            # ingredient.recipe = recipe
            # ingredient.save()
            return redirect('recipes:index')
    else:
        formRecipe = RecipeForm()
        formset = ingredientFormSet()
    args = {}
    args['formRecipe'] = formRecipe
    args['formset'] = formset
    return render(request, 'recipes/new_recipe.html', args)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Django Project</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'recipes/style.css' %}">
  </head>
<body>

    {% block content %}

    {% endblock %}
    <script src="{% static 'index.js' %}"></script>
</body>
</html>

templates/recipes/index.html
{% extends "base.html" %}

{% block content %}

<h1>Welcome to the Recipe interface</h1>
<button type="button" class="btn btn-primary" id="add-recipe" onclick="location.href='/recipe/new/'">Add a new recipe</button>
{% if recipe_list %}
    <ul>
    {% for recipe in recipe_list %}
        <li><img class="recipe-image" src="{{recipe.photo.url}}" alt="{{ recipe.name }}"><div id="text"><a href="/recipe/{{ recipe.id }}/">{{ recipe.name }}</a></div></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recipes are available.</p>
{% endif %}

{% endblock %}

templates/recipes/new_recipe.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>Add a new recipe</h1>

  <form id="form-container" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ formRecipe.as_p }}
    <h2>Add Ingredients</h2>
    {{ formset.management_form }}
    <ul class="ingredient-form">
      {% for form in formset %}
      <li>
        {{ form }}
      </li>
      {% endfor %}
    </ul>
    <button id="add-form" type="button">Add Another Ingredient</button>
    <br>
    <br>
    <input type="submit" value="Submit">
  </form>
</div>
<a href="/">Go back</a>

{% endblock %}

templates/recipes/recipe_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>{{recipe.name}}</h1>
  <img id="recipe" src="{{recipe.photo.url}}" alt="{{ recipe.name }}">

  <p>{{recipe.description}}</p>
  <h2>Ingredients</h2>
  <ul>
    {% for ingredient in recipe.ingredient_set.all %}
    <li>{{ingredient.quantity}}: {{ingredient.ingredientName}}</li>
    {% endfor %}
  </ul>
  <h2>Instructions</h2>
  <p>{{recipe.instructions}}</p>


  <h2>Reviews</h2>
  {% if recipe.review_set.all %}
  <h3>{{recipe.review_set.all.count}} Review</h3>
  {% for review in recipe.review_set.all %}
  <div>
    <h3>{{review.title}}</h3>
    <p>{{review.comment}}</p>
    <p>Rating: {{review.rating}}/5</p>
  </div>
  {% endfor %}
  {% else %}
  <p>No reviews available.</p>
  {% endif %}

  <h2>Write a review</h2>
  <form action="{% url 'recipes:add_review' recipe.id %}" method="post">
    {% csrf_token %}
    <div>
      <label for="title">Title</label>
      <textarea name="title" id="title" cols="30" rows="1"></textarea>
    </div>
    <div>
      <label for="comment">Comment</label>
      <textarea name="comment" id="comment" cols="30" rows="10"></textarea>
    </div>
    <div>
      <!-- Add rating input -->
      <label for="rating">Rating</label>
      <input type="number" name="rating" id="rating" min="1" max="5">
    </div>
    <div>
      <input type="submit" value="Submit">
    </div>
  </form>
  <br>
  <a href="/"><button>Go back</button></a>
</div>



{% endblock %}